# -*- coding: utf-8 -*-
"""final pap smear code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cu6JX4Z83c4pz4YHQE5JxLPfzbVnMCWo
"""

!pip install timm grad-cam gradio

from google.colab import drive
drive.mount('/content/drive')

import torch
print(torch.cuda.is_available())

import os
print(os.listdir('/content/drive/MyDrive'))

!pip install kaggle

!mkdir -p ~/kaggle
!cp kaggle.json ~/.kaggle./
!kaggle datasets download -d prahladmehandiratta/cervical-cancer-largest-dataset-sipakmed
!unzip cervical-cancer*.zip -d /content/drive/MyDrive/sipakmed

import os
path = '/content/drive/MyDrive/sipakmed'
print(os.listdir(path))

import timm
import torch

# โหลดโมเดล ViT สำเร็จรูป
model = timm.create_model('vit_base_patch16_224',
                           pretrained=True,
                           num_classes=5)
model = model.cuda()
print("โมเดลพร้อมแล้ว!")
print(model)

from torchvision import datasets, transforms
from torch.utils.data import DataLoader # Corrected import

# แปลงรูปให้พร้อม train
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])

# โหลด dataset
dataset = datasets.ImageFolder(
    '/content/drive/MyDrive/sipakmed',
    transform=transform
)

# แบ่ง train/test 80/20
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_data, test_data = torch.utils.data.random_split(dataset, [train_size, test_size])

train_loader = DataLoader(train_data, batch_size=32, shuffle=True)
test_loader = DataLoader(test_data, batch_size=32) # Corrected batch_size

print(f"รูปทั้งหมด: {len(dataset)}")
print(f"Train: {train_size}, Test: {test_size}")

!rm /content/cervical-cancer-largest-dataset-sipakmed,zip

import torch.nn as nn
import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(3):
    model.train()
    total_loss = 0
    for images, labels in train_loader:
        images, labels = images.cuda(), labels.cuda()
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}: Loss = {total_loss/len(train_loader):.4f}")

torch.save(model.state_dict(),
'/content/drive/MyDrive/sipakmed/model.pth')
print("เซฟเสร็จแล้ว!")

!pip install timm grad-cam gradio

from google.colab import drive
drive.mount('/content/drive')

import timm
import torch

model = timm.create_model('vit_base_patch16_224',
                           pretrained=False,
                           num_classes=5)
model.load_state_dict(torch.load('/content/drive/MyDrive/sipakmed/model.pth'))
model = model.cuda()
model.eval()
print("โหลดโมเดลสำเร็จ!")

import os
print(os.listdir('/content/drive/MyDrive'))

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir('/content/drive/MyDrive'))

import timm
import torch

model = timm.create_model('vit_base_patch16_224',
                           pretrained=False,
                           num_classes=5)
model = model.cuda()
print("พร้อมแล้ว!")

import os

print(os.path.exists('/content/drive/MyDrive/sipakmed'))

from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.5], [0.5])
])
dataset = datasets.ImageFolder('/content/drive/MyDrive/sipakmed', transform=transform)
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_data, test_data = torch.utils.data.random_split(dataset, [train_size, test_size])
train_loader = DataLoader(train_data, batch_size=32)
print(f"รูปทั้งหมด: {len(dataset)}")

import torch.nn as nn
import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

for epoch in range(3):
    model.train()
    total_loss = 0
    for images, labels in train_loader:
        images, labels = images.cuda(), labels.cuda()
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}: Loss = {total_loss/len(train_loader):.4f}")

from torch.utils.data import DataLoader

train_loader = DataLoader(dataset, batch_size=32, num_workers=2, pin_memory=True)

!ls "/content/drive/MyDrive"

from google.colab import drive
drive.mount('/content/drive')

import os
for root, dirs, files in os.walk('/content/drive/MyDrive'):
    for f in files:
        if f.endswith('.pth'):
            print(os.path.join(root, f))

import torch
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.cuda(), labels.cuda()
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()

accuracy = 100 * correct / total
print(f"ความแม่นยำ: {accuracy:.2f}%")

import os

for root, dirs, files in os.walk("/content/"):
  for file in files:
    if file.endswith(".pth"):
      print(os.path.join(root, file))

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.path.exists("/content/drive/MyDrive/sipakmed/model.pth"))

from google.colab import files
files.download("/content/drive/MyDrive/sipakmed/model.pth")

from google.colab import files
uploaded = files.upload()

!pip install -q gradio

import torch
import timm
import gradio as gr
from PIL import Image
from torchvision import transforms

model = timm.create_model(
    "vit_base_patch16_224",
    pretrained=False,
    num_classes=5
)

model.load_state_dict(torch.load("model.pth" , map_location="cpu"))
model.eval()

class_names = [
    "NILM (Negative for Intraepithelial Lesion or Malignancy)",
    "ASC-US (Atypical Squamous Cells of Undetermined Significance)",
    "LSIT (Low-Grade Squamous Intraepithelial Lesion)",
    "HSIL (High-Grade Squamous Intraepithelial Lesion)",
    "SCC (Squamous Cell Carcinoma)"
]

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    ])

def predict(image):
  x = transform(image).unsqueeze(0)

  with torch.no_grad():
    y = model(x)
    probs = torch.softmax(y, dim=1)[0]

    return {
        class_names[i]: float(probs[i])
        for i in range(len(class_names))
    }
demo = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil"),
    outputs=gr.Label(num_top_classes=5),
    title="Pap Smear AI"
)

demo.launch(share=True)

import os

print(os.listdir())

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

title="Pap Smear AI - Cervical Cell Classification"

input = gr.Image(type="pil")

outputs = gr.Label(label="Prediction")

description="อัปโหลดภาไ Pap Smear เพื่อให้ AI วิเคราะห์"

demo.launch(share=True)

demo = gr.Interface(
    fn=predict,
    inputs=gr.Image(
        type="pil",
        label="📤 Upload Pap Smear Image"
    ),
    outputs=gr.Label(
        label="🔬 AI Analysis Result"
    ),
    title="🩺 Pap Smear AI Classifier",
    description="""
### Cervical Cell Classification using Vision Transformer (ViT)
อัปโหลดภาพ Pap Smear เพื่อให้ระบบ AI วิเคราะห์ประเภทของเซลล์
**ผลลัพธ์ที่รองรับ**
- 🟢 NILM (Normal)
- 🟡 ASC-US
- 🟠 LSIL
- 🟠 HSIL
- 🔴 SCC
""",
    article="""
---
### ⚠️ Medical Disclaimer
ผลลัพธ์นี้เป็นการประเมินโดยปัญญาประดิษฐ์ (AI) เพื่อช่วยสนับสนุนการวิเคราะห์เบื้องต้นเท่านั้น
**ไม่ใช่การวินิจฉัยทางการแพทย์** และไม่ควรใช้แทนการประเมินของแพทย์หรือผู้เชี่ยวชาญด้านพยาธิวิทยา
ผู้ใช้งานควรให้บุคลากรทางการแพทย์ตรวจสอบและยืนยันผลทุกครั้งก่อนนำไปใช้ในการตัดสินใจทางการแพทย์
"""
)
demo.launch(share=True)

# ติดตั้ง (รันครั้งเดียวใน Colab)
!pip install -q timm gradio
import torch
import timm
import gradio as gr
from PIL import Image
from torchvision import transforms
# =========================
# สร้างโมเดล
# =========================
model = timm.create_model(
    "vit_base_patch16_224",
    pretrained=False,
    num_classes=5
)
# โหลดโมเดลที่เทรนไว้
model.load_state_dict(torch.load("model.pth", map_location="cpu"))
model.eval()
# =========================
# ชื่อคลาส
# =========================
class_names = [
    "NILM (Negative for Intraepithelial Lesion or Malignancy)",
    "ASC-US (Atypical Squamous Cells of Undetermined Significance)",
    "LSIL (Low-Grade Squamous Intraepithelial Lesion)",
    "HSIL (High-Grade Squamous Intraepithelial Lesion)",
    "SCC (Squamous Cell Carcinoma)"
]
# =========================
# เตรียมรูปภาพ
# =========================
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])
# =========================
# ฟังก์ชันทำนาย
# =========================
def predict(image):
    image = transform(image).unsqueeze(0)
    with torch.no_grad():
        output = model(image)
        probs = torch.softmax(output, dim=1)[0]
    return {
        class_names[i]: float(probs[i])
        for i in range(len(class_names))
    }
# =========================
# สร้างเว็บ Gradio
# =========================
demo = gr.Interface(
    fn=predict,
    inputs=gr.Image(
        type="pil",
        label="📤 Upload Pap Smear Image"
    ),
    outputs=gr.Label(
        label="🔬 AI Analysis Result",
        num_top_classes=5
    ),
    title="🩺 CerviVision AI",
    description="""
## AI-powered Pap Smear Classification
อัปโหลดภาพ Pap Smear เพื่อให้ AI วิเคราะห์ประเภทของเซลล์
รองรับการจำแนก:
• NILM
• ASC-US
• LSIL
• HSIL
• SCC
""",
    article="""
---
### ⚠️ Medical Disclaimer
ผลลัพธ์นี้เป็นการประเมินโดยปัญญาประดิษฐ์ (AI)
เพื่อช่วยสนับสนุนการวิเคราะห์เบื้องต้นเท่านั้น
ไม่ใช่การวินิจฉัยทางการแพทย์
และไม่ควรใช้แทนการประเมินของแพทย์หรือผู้เชี่ยวชาญด้านพยาธิวิทยา
ควรให้บุคลากรทางการแพทย์ตรวจสอบและยืนยันผลทุกครั้งก่อนนำไปใช้ในการตัดสินใจทางการแพทย์
""",
    theme=gr.themes.Soft()
)
# เปิดเว็บ
demo.launch(share=True)

import gradio as gr
custom_theme = gr.themes.Soft(
    primary_hue="amber",
    secondary_hue="neutral",
    neutral_hue="stone",
).set(
    body_background_fill="#F8F4EC",      # ครีมอ่อน
    block_background_fill="#FFFDF9",     # ขาวครีม
    block_border_color="#D8C3A5",        # น้ำตาลอ่อน
    button_primary_background_fill="#A67C52",  # น้ำตาลคาราเมล
    button_primary_text_color="white",
    button_primary_border_color="#8B6B4A",
)
demo = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil", label="📤 Upload Pap Smear Image"),
    outputs=gr.Label(label="🔬 AI Analysis Result", num_top_classes=5),
    title="Cervix AI",
    description="""
## AI-Powered Pap Smear Classification
อัปโหลดภาพ Pap Smear เพื่อให้ AI ช่วยวิเคราะห์ประเภทของเซลล์
""",
    article="""
⚠️ **Medical Disclaimer**
ผลลัพธ์นี้เป็นการประเมินโดยปัญญาประดิษฐ์ (AI) เพื่อช่วยสนับสนุนการวิเคราะห์เบื้องต้นเท่านั้น
ไม่ใช่การวินิจฉัยทางการแพทย์ และควรได้รับการยืนยันโดยบุคลากรทางการแพทย์ก่อนนำไปใช้ในการตัดสินใจทางคลินิก
""",
    theme=custom_theme,
)
public_url = ngrok.connect(7860)
print("🔗 ลิงก์เว็บถาวรของคุณคือ:", public_url.public_url)

demo.launch(inline=False)

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir())

!pip install pyngrok
from pyngrok import ngrok
ngrok.set_auth_token("3F9ctuJf3ZzXFly9QNoI2cvrFKF_7LB72mbddm9hQ2aNWANZ1")